const { faker } = require("@faker-js/faker");

module.exports = () => {
  return new Array(120).fill(undefined).map((_, index) => ({
    id: index + 1,
    first_name: faker.name.firstName(),
    last_name: faker.name.lastName(),
    email: faker.internet.email(),
    driver: faker.datatype.number(),
    vehicle: faker.random.numeric(5),
    username: faker.internet.userName(),
    co_driver: faker.name.fullName(),
    notes: faker.random.words(2),
    app_version: faker.datatype.float({ max: 5 }),
    activated: faker.date.recent(),
    terminated: faker.date.recent(),
    device: faker.vehicle.vehicle(),
    status: faker.datatype.boolean(),
    lat: faker.address.latitude(),
    lon: faker.address.longitude(),
    truck_num: faker.vehicle.vrm(),
    device_num: faker.vehicle.vin(),
    cur_speed: faker.datatype.number({ min: 0, max: 300 }),
    operating_sys: faker.helpers.arrayElement(["iOS", "Android"]),
    phone_number: faker.phone.number("+998-##-###-##-##"),
    license_number: faker.random.numeric(7),
    terminal_address: faker.address.secondaryAddress(),
    terminal_time_zone: faker.address.timeZone(),
    trailer_number: faker.random.numeric(3),
    enableEld: faker.datatype.boolean(),
    enableELog: faker.datatype.boolean(),
    allowYardMove: faker.datatype.boolean(),
    allowConveyance: faker.datatype.boolean(),
    allowManualDrive: faker.datatype.boolean(),
    license_state: faker.address.state(),
    enable_eld: faker.datatype.boolean(),
    enable_e_log: faker.datatype.boolean(),
    allow_yard_move: faker.datatype.boolean(),
    allow_conveyance: faker.datatype.boolean(),
    allow_manual_drive: faker.datatype.boolean(),
  }));
};
